name: Automated Campus Attendance System

on:
  schedule:
    # --- TUESDAY ---
    - cron: '5 1 * * 2'   # 08:05 WIB (Patient Mode)
    - cron: '35 3 * * 2'  # 10:35 WIB (Patient Mode)
    - cron: '5 6 * * 2'   # 13:05 WIB (Patient Mode)
    - cron: '35 8 * * 2'  # 15:35 WIB (Instant Mode)

    # --- WEDNESDAY ---
    - cron: '5 1 * * 3'   # 08:05 WIB (Patient Mode)
    - cron: '35 3 * * 3'  # 10:35 WIB (Instant Mode)
    - cron: '5 6 * * 3'   # 13:05 WIB (Patient Mode)
    - cron: '50 7 * * 3'  # 14:50 WIB (Instant Mode)

    # --- SATURDAY ---
    - cron: '35 3 * * 6'  # 10:35 WIB (Patient Mode)
    - cron: '5 6 * * 6'   # 13:05 WIB (Patient Mode)
    - cron: '35 8 * * 6'  # 15:35 WIB (Instant Mode)

    # --- NIGHTLY SWEEP (Tue, Wed, Sat) ---
    - cron: '0 14 * * 2,3,6' # 21:00 WIB (Instant Mode)

  workflow_dispatch:

jobs:
  attendance-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install selenium requests

      - name: Execute Attendance Script
        env:
          NIM_KAMPUS: ${{ secrets.NIM_KAMPUS }}
          PW_KAMPUS: ${{ secrets.PW_KAMPUS }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PYTHONUNBUFFERED: 1
        run: python bot_absen_cloud.py
